# This is the configuration file for the spell tagger

[en-US.spell-name]
previouslyRegex = "^<!-- previously \\\"(.*)\\\" -->$"

[en-US.spell-type]
cantripRegex = "^_(\\w+) cantrip_$"
leveledSpellRegex = "^_(\\d).?.?-level (\\w+)_$"
ritualRegex = "^_(\\d).?.?-level (\\w+) \\(ritual\\)_$"

[en-US.casting]
castingTimeRegex = "^\\*\\*Casting Time:\\*\\* (\\d+) (action|bonus action|reaction|minutes?|hours?),?\\s?(.*) \\\\$"

[en-US.range]
rangeDistanceRegex = "^\\*\\*Range:\\*\\* (\\d+) (\\w+) \\\\$"
rangeSelfRegex = "^\\*\\*Range:\\*\\* Self \\(?([\\d\\w\\s\\-]+)?\\)?\\s?\\\\$"
self = "Self"
rangeTouchRegex = "^\\*\\*Range:\\*\\* Touch \\\\$"
touch = "Touch"
rangeSpecialRegex = "^\\*\\*Range:\\*\\* Special \\\\$"
special = "Special"

[en-US.components]
componentsRegex = "^\\*\\*Components:\\*\\* ([VSM]),?\\s?([VSM])?,?\\s?([VSM])?\\s?\\(?([\\w\\d\\s,â€™\\-]*)?\\)? \\\\$"

[en-US.duration]
durationInstantRegex = "^\\*\\*Duration:\\*\\* Instantaneous$"
instantaneous = "Instantaneous"
durationNoConcentrationRegex = "^\\*\\*Duration:\\*\\* (\\d+) (\\w+)$"
durationConcentrationRegex = "^\\*\\*Duration:\\*\\* Concentration, up to (\\d+) (\\w+)\\n$"
durationOtherRegex = "^\\*\\*Duration:\\*\\* ([\\w\\s]+)\\n$"
